### ISSUE TITLE
install_ansible_roles.sh not present in the repository

### ISSUE THREAD

**Issue by darwinrc** [sysco-middleware/packer-oracle-soa#3]
I cannot deploy the machine because that file is not in the repository

**Comment by jeqo** [comment]
Hi @darwinrc ,

I just updated the README.md file. You only have to execute:

```
ansible-galaxy install -f -p ./roles -r roles.yml
```

Let me know if it works ok.

**Comment by darwinrc** [comment]
Good day @jeqo It worked well. Thanks for your quick response! I'm proceeding to close the issue.
